[package]
name = "org-server"
version = "0.1.0"
edition = { workspace = true }

[[bin]]
path = "src/main.rs"
name = "org-server"

[dependencies]
org-parser = { path = "../parser" }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
axum = { version = "0.8", features = ["http1", "tokio", "json", "query"], default-features = false }
tokio = { version = "1.0", features = ["fs", "io-util", "rt-multi-thread", "signal"] }
clap = { version = "4", features = ["derive", "std"], default-features = false }
globmatch = "0.3"
regex = { workspace = true }
toml = { version = "0.8", features = ["parse"], default-features = false }
xdg = "2"
walkdir = "2"
futures = { version = "0.3", default-features = false }
notify-rust = { version = "4", features = ["serde", "zbus"], default-features = false }
zbus = { version = "5", default-features = false, features = ["tokio"] }
notify = { version = "8", default-features = false }
thiserror.workspace = true
tower = "0.5"
rmcp = { version = "=0.6.4", features = ["transport-sse-server"] }
rmcp-macros = "0.6.4"
tokio-util = "0.7"
notify-debouncer-mini = "0.7.0"
ignore = "0.4.25"
schemars = "1.2.1"
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tempfile = "3.8"
tower = "0.5"
